// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'play/views/controls/switch', 'play/models/controlModel'], function($, _, Backbone, SwitchView, ControlModel) {
    var ControllerView;

    ControllerView = Backbone.View.extend({
      className: 'controller',
      initialize: function() {
        console.log('new controller view!');
        console.log(this.model);
        this.listenTo(this.model, 'controller:load', this.pickSizes);
        return this.model.fetchData();
      },
      render: function() {
        var _this = this;

        this.model.collection.each(function(elem, idx) {
          var ViewProto, controlView;

          ViewProto = elem.get('viewProto');
          console.log(_this.model.socket);
          controlView = new ViewProto({
            model: elem,
            controldims: _this.controldims
          });
          return _this.$el.append(controlView.render());
        });
        return $('#page').html(this.el);
      },
      pickSizes: function() {
        var height, width;

        width = window.outerWidth;
        console.log(width);
        height = window.outerHeight;
        if (width < 450) {
          this.controldims = {
            width: width / 2,
            height: width / 2
          };
        } else if (width < 738) {
          this.controldims = {
            width: width / 3,
            height: width / 3
          };
        } else {
          this.controldims = {
            width: width / 4,
            height: width / 4
          };
        }
        this.controldims.icon = this.controldims.width / 3;
        this.controldims.text = this.controldims.width / 12;
        return this.render();
      }
    });
    return ControllerView;
  });

}).call(this);
