// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var ControlModel;

    ControlModel = Backbone.Model.extend({
      defaults: {
        icon: 'icon-arrow-up',
        'name-display': 'Some Name'
      }
    });
    return ControlModel;
  });

}).call(this);
