// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'play/views/controls/base'], function($, _, Backbone, BaseView) {
    var AccelerometerView;

    AccelerometerView = BaseView.extend({
      onclick: function() {
        var _this = this;

        this.$el.addClass('control-active');
        return setTimeout(function() {
          return _this.$el.removeClass('control-active');
        }, 200);
      }
    });
    return AccelerometerView;
  });

}).call(this);
