// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone', 'views/control'], function($, _, Backbone, ControlView) {
    var ControlModel;

    ControlModel = Backbone.Model.extend({
      defaults: {
        prefix: '',
        icon: 'icon-move'
      },
      initialize: function() {
        var controlView;

        console.log('control model init');
        return controlView = new ControlView({
          model: this
        });
      }
    });
    return ControlModel;
  });

}).call(this);
