// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var ControlsCollection;

    ControlsCollection = Backbone.Collection.extend({
      initialize: function() {
        return console.log('new controls collection');
      }
    });
    return ControlsCollection;
  });

}).call(this);
