// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var ControlsCollection;

    ControlsCollection = Backbone.Collection.extend({
      initialize: function() {
        return console.log('controls collection initialized');
      },
      addControl: function(e, ui) {
        console.log('add a new control');
        return ui.item.trigger('drop', [this]);
      },
      sortUpdate: function(e, ui) {
        console.log('sort and update');
        return this.forEach(function(model) {
          return console.log(model);
        });
      }
    });
    return ControlsCollection;
  });

}).call(this);
